use_frameworks!

platform :ios, '10.0'

target 'CarouselLayout_Example' do
  pod 'CarouselLayout', :path => '../'

  target 'CarouselLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
